name: SmartBookshelfViewer
version: '${version}'
author: MiniMoro
main: it.moro.minimoro.ChiseledBookshelfViewer
api-version: '1.21'

commands:
  bookshelf:
    description: Main command

permissions:
  smartbookshelf.*:
    description: Gives access to all SmartBookshelfViewer permissions
    default: op
    children:
      smartbookshelf.reload: true
      smartbookshelf.setmode: true
      smartbookshelf.use: true

  smartbookshelf.reload:
    description: Permission to reload configuration
    default: false

  smartbookshelf.setmode:
    description: Permission to change output mode
    default: false

  smartbookshelf.use:
    description: Permission to use the plugin
    default: true